### ISSUE TITLE
질문있습니당

### ISSUE THREAD

**Issue by thsdudals208** [MetaGroup0506/practice#68]
![스크린샷(61)](https://github.com/MetaGroup0506/practice/assets/169255823/bd330757-dcb7-4d89-8d65-ee8fda54a265)
똑같이 따라도해보고 생각도해봤는데  z 값이 0에서 올라가질않네요 뭐가잘못된거죠ㅠ,ㅠ

**Comment by thsdudals208** [comment]
toCharArray사용해서 해결은 했는데 
저상태에서 carr 값을 넣을 방법이 있을까요

**Comment by monkey-ohgiraffers** [comment]
처음에 작성하신 소스에서 비교가 일어나지 않았던 이유는 비교할 대상을 넣어주지 않아서입니다.
처음에 작성하신 char[] carr = new char[str.length()] 이렇게 입력한 문자열의 길이만큼 배열의 방을 만들어주신것까지는 잘하셨는데요. 만든 방에 값을 넣어주는 소스가 없어서 아래의 조건절에서 걸리는게 없다고 나오는거에요~ 그래서 char[] carr = new char[str.length()]; 이후에 for(int i = 0; i < carr.length; i++) { carr[i] = str.charAt(i)} 이렇게 초기화하는 코드가 들어가야합니다~
